Fixed the validation error when 'attributes' value is a dict
